# ==============================================================================
# golangci-lint 配置文件
# 用于 Go 代码的静态分析和代码质量检查
# ==============================================================================

# 配置文件版本（v2）
version: "2"

# ==============================================================================
# 运行配置
# ==============================================================================
run:
  # Go 版本要求
  go: "1.24"
  # 单个 linter 的超时时间
  timeout: 10m
  # 允许并行运行多个 linter（提高检查速度）
  allow-parallel-runners: true

# ==============================================================================
# Linter 配置
# ==============================================================================
linters:
  # 默认不启用任何 linter，只使用下面 enable 列表中的 linter
  default: none

  # 排除检查的目录路径（这些目录中的代码不会被检查）
  exclusions:
    paths:
      - "ui/"          # 前端 UI 代码目录
      - ".vscode/"     # VS Code 配置目录
      - ".claude/"
      - ".idea/"       # JetBrains IDE 配置目录
      - ".github/"    # GitHub 配置目录

  # 启用的 Linter 列表
  enable:
    # ============================================================================
    # 安全相关
    # ============================================================================
    - asasalint      # 检查 os/exec 命令执行的安全性
    - bidichk        # 检查双向字符（可能的安全问题）

    # ============================================================================
    # 代码质量
    # ============================================================================
    - asciicheck     # 检查非 ASCII 字符的使用
    - bodyclose      # 检查 HTTP 响应体是否关闭
    - copyloopvar    # 检查循环变量在闭包中的使用问题
    - dogsled        # 检查函数参数过多（超过 7 个参数）
    # - forbidigo      # 禁止使用指定的函数（如 fmt.Print 等调试函数）
    # 暂时禁用 forbidigo，因为正则表达式匹配范围过广，会误报
    # 可以使用 lefthook.yml 中的 no-debug hook 来检查 fmt.Print
    - gocritic       # Go 代码建议和优化
    - gocyclo        # 检查函数圈复杂度（函数复杂度过高）
    - goprintffuncname # 检查 printf 函数命名规范
    - ineffassign    # 检查无效赋值（赋值后未使用）
    - makezero       # 检查 make 切片/映射时是否指定容量
    - nakedret       # 检查裸返回（return 语句没有显式返回值）
    - nolintlint     # 检查 nolint 注释的使用是否正确
    - unconvert      # 检查不必要的类型转换
    - unparam        # 检查未使用的函数参数
    - unused         # 检查未使用的代码（变量、函数、类型等）
    - whitespace     # 检查空白字符问题（多余的空行等）
    - revive         # 检查代码风格和命名规范

    # ============================================================================
    # 错误处理
    # ============================================================================
    - errcheck       # 检查错误是否被处理（必须检查返回的 error）
    - errchkjson     # 检查 JSON 序列化/反序列化的错误处理
    - errorlint      # 检查错误处理的最佳实践
    - nilerr         # 检查返回 nil 错误的情况

    # ============================================================================
    # 测试相关
    # ============================================================================
    - ginkgolinter   # Ginkgo 测试框架的 linter

    # ============================================================================
    # 标准工具
    # ============================================================================
    - govet          # Go 官方 vet 工具（内置静态分析，对应 go vet 命令）
    - staticcheck    # 强大的静态分析工具（替代 go vet 的增强版）

    # ============================================================================
    # 导入和拼写
    # ============================================================================
    - importas       # 检查导入别名使用
    - misspell       # 检查英文单词拼写错误

    # ============================================================================
    # 代码重复
    # ============================================================================
    - dupl           # 检测重复代码块

# ==============================================================================
# Linter 特定设置
# ==============================================================================
  settings:
    # Staticcheck 配置（Go 静态分析工具）
    staticcheck:
      checks:
        # 启用所有检查
        - "all"
        # ============================================================================
        # 命名和风格相关规则（由 revive 处理，更灵活）
        # ============================================================================
        - "-ST1000" # 禁用：包注释检查（包必须有注释）
        - "-ST1003" # 禁用：命名检查（变量、函数命名规范）
        - "-ST1020" # 禁用：导出函数注释格式检查
        - "-ST1021" # 禁用：导出类型注释格式检查
        - "-ST1022" # 禁用：导出变量注释格式检查
        - "-SA1029" # 禁用：context key 类型检查（项目中多处使用字符串 key，为保持兼容性）

        # 代码简化相关规则
        - "-QF1001" # 禁用：德摩根定律简化
        - "-QF1008" # 禁用：未使用的参数检查（由 unparam 处理）

    # Dupl 配置（重复代码检测）
    dupl:
      threshold: 500      # 最大 token 数（超过此数量的重复代码才会报告）
      min-similarity: 80  # 最小相似度百分比（80% 以上相似才认为是重复）

    # Gocyclo 配置（函数圈复杂度检查）
    gocyclo:
      min-complexity: 100  # 函数圈复杂度阈值（超过此值会报告）

    # Revive 配置（代码风格、命名规范和错误处理风格）
    # 从 revive.toml 迁移过来的配置
    revive:
      # 基本配置
      ignore-generated-header: false  # 不忽略生成的文件头
      severity: warning                # 严重程度：warning
      confidence: 0.8                  # 置信度阈值
      error-code: 1                    # 发现 error 级别问题时退出码为 1（阻止提交）
      warning-code: 0                  # 发现 warning 级别问题时退出码为 0

      # 规则配置
      rules:
        # ============================================================================
        # 导入相关规则
        # ============================================================================
        - name: blank-imports      # 禁止空白导入
        - name: dot-imports        # 禁止点导入（如 import . "fmt"）

        # ============================================================================
        # Context 相关规则
        # ============================================================================
        - name: context-as-argument  # context 应作为第一个参数
        - name: context-keys-type    # context keys 应使用自定义类型

        # ============================================================================
        # 错误处理相关规则（Revive 擅长）
        # ============================================================================
        - name: error-return        # 检查错误返回值
        - name: error-strings       # 错误字符串不应大写或包含标点
        - name: error-naming        # 错误变量命名规范（err, Err 等）
        - name: errorf              # 使用 Errorf 而不是 Error + fmt.Sprintf
        - name: indent-error-flow   # 错误处理流程的缩进规范

        # ============================================================================
        # 命名规范规则（Revive 擅长，staticcheck 已禁用相关规则）
        # ============================================================================
        # var-naming 规则已禁用，因为项目中存在 ID/Id 两种命名风格
        # revive 的 var-naming 规则不支持配置来忽略特定命名模式（如 ID/Id）
        # ignored-names 配置项可能只对局部变量有效，对函数参数、方法名等无效
        # 因此只能完全禁用该规则，以允许项目中同时使用 ID 和 Id 两种命名风格
        - name: var-naming
          disabled: true
        - name: receiver-naming     # 接收器命名规范（与 staticcheck ST1006 重叠，但 revive 更灵活）
        - name: time-naming         # 时间相关变量命名规范
        - name: redefines-builtin-id # 禁止重定义内置标识符

        # ============================================================================
        # 代码风格规则
        # ============================================================================
        - name: var-declaration     # 变量声明风格
        - name: if-return           # if 后直接 return 的风格
        - name: increment-decrement # 自增自减操作规范
        - name: range                # range 循环使用规范
        - name: empty-block         # 禁止空代码块
        - name: superfluous-else    # 禁止多余的 else（与 staticcheck S1023 类似但不同）
        - name: unexported-return   # 未导出函数的返回值规范

        # ============================================================================
        # 已禁用的规则（由 staticcheck 或其他工具处理）
        # ============================================================================
        # exported: 导出函数注释（可选，如果团队需要可启用）
        # package-comments: 包注释（已禁用，不强制要求包注释）
        - name: package-comments
          disabled: true

        # ============================================================================
        # 与 staticcheck 重叠的规则（已移除，由 staticcheck 处理）
        # ============================================================================
        # unused-parameter: 未使用参数 - 由 staticcheck U1000 系列处理（更全面）
        # unreachable-code: 不可达代码 - 由 staticcheck 处理（更准确）
